pipeline {
    agent  any 

    tools {
        maven 'Maven'  // name of the Maven installation from Global Tool Configuration
        // You can also add JDK here if needed
        
    }

    environment {
        DOCKER_IMAGE = "rukevweubio/java-app"
        image_tag = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo "Checkout completed successfully"
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
                echo " Maven build completed successfully"
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn test'
                echo "Tests ran successfully"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${image_tag}")
                    echo "Docker image built successfully"
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("${DOCKER_IMAGE}:${image_tag}").push()
                        echo "Docker image pushed to DockerHub successfully"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "🎉 Pipeline finished successfully!"
        }
        failure {
            echo " Pipeline failed. Check the logs for errors."
        }
    }
}
